import { Plugin } from 'jsonic';
declare type Term = {
    name: string;
    src: string;
    left: number;
    right: number;
    use: any;
    prefix: boolean;
    suffix: boolean;
    infix: boolean;
    ternary: boolean;
    paren: boolean;
    terms: number;
    tkn: string;
    tin: number;
    osrc: string;
    csrc: string;
    otkn: string;
    otin: number;
    ctkn: string;
    ctin: number;
    preval: {
        active: boolean;
        required: boolean;
    };
};
declare let Expr: Plugin;
declare function prattify(expr: any, op?: Term): any[];
declare function evaluate(expr: any, resolve: (op: Term, ...terms: any) => any): any;
export { Expr, prattify, evaluate, };
export type { Term };
